export interface ItemList {
    mode: string,
    stockID: number,
    productName: string,
    generic: string,
    itemDescription: string,
    leaf:number,
    unit: number,
    totalUnit: number,
    stockQty: number,
    freeUnit: number,
    supplierBonus: number,
    batchNo: string,
    packSize: number,
    sheetSize: number,
    purchasePrice: number,
    originalPPrice: number,
    sellingPrice: number,
    originalSPrice: number,
    mrp: number,
    brandName: string,
    sectorName: string,
    categoryName: string,
    productType: string,
    expiryDate: string,
    itemDisc: number,
    tax1: number,
    tax2: number,
    tax3: number,
    subTotal: number
}